print ("    _____   ")
print ("   /     \\")
print ("  | [] [] |")
print ("  |   ^   |")
print ("  |  ---  |")
print ("   \_____/")
print ("    _____")
print ("   /     \\")
print ("  | [] [] |")
print ("  |   ^   |")
print ("  |  ---  |")
print ("   \_____/")
